---
name: Test Node with workflow
on:
  push:
    branches:
      - main
jobs:
  first-job:
    name: Build with Node
    runs-on: ubuntu-latest
    container: node:12.18.4
    steps:
      - name: Check Node.js version
        run: node --version
      - name: Check NPM version
        run: npm --version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Execute Node application
        run: node index.js
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  coverity:
    runs-on: ubuntu-latest
    steps:
      - name: Unofficial Coverity Scan
        uses: vapier/coverity-scan-action@v1
        with: null
        token: RA216bvK-lldAFU8ZP-syQ
        email: venkat.kurukuntla@gmail.com
        build_language: JavaScript
        build_platform: null
        command: null



